time_format = "%Y-%m-%d %H:%M:%S"
time_format_names = "%Y%m%d_%H%M%S"
pipeline_start_time_label = "Pipeline Start Time: "
pipeline_end_time_label = "Pipeline End Time: "
global_logfile = "/logfile.log"